### ISSUE TITLE
Is there a way to get the user made an action?

### ISSUE THREAD

**Issue by sguryev** [OfficeDev/outlook-actionable-messages-csharp-token-validation#9]
Hello,

I'm trying to solve the task with passing the actor to the HttpPOST action from the card in Teams.
So once user clicked on action I can use Inputs for getting user input and add it to the POST action this way:
```
{
  "@type": "ActionCard",
  "name": "Comment",
  "inputs": [
    {
      "@type": "TextInput",
      "id": "comment",
      "isMultiline": true,
      "title": "Input's title property"
    }
  ],
  "actions": [
    {
      "@type": "HttpPOST",
      "name": "Action's name prop.",
      "target": "https://yammer.com/comment?postId=123",
      "body": "comment={{comment.value}}"
    }
  ]
}
```

But I would like to add some user information (name, email, whatever).
### Do we have some predefined variables can be used for it?

**Side Notes:**
1. Connector posts the reply to the card after the success response from the HttpPOST action containing the actor name (so it looks promising): 
![image](https://user-images.githubusercontent.com/6978458/50147661-c944fd80-02c7-11e9-822c-6c4772b254f4.png)
2. Connector passes the `access_token` to the HttpPOST API endpoint which contains some information (sub, tid). But there is no any scopes so even I will found the correct `userprofile` endpoint for STS I will not be able to call it
![image](https://user-images.githubusercontent.com/6978458/50147898-3f496480-02c8-11e9-92fc-30e183623f6e.png)
3. Based on the sample I was able to use the `ActionableMessageTokenValidator` but the result is useless (shows the same `sub` only (I saw in the token)):
![image](https://user-images.githubusercontent.com/6978458/50159573-133ddb80-02e8-11e9-9607-142b1eab0e8b.png)

**Comment by MacroPower** [comment]
I'm not using C# but I would also like to see some way to include this in the response body. Seems like there definitely should be something pre-defined.

**Comment by surebert** [comment]
Has anyone figured out a way to do this?

**Comment by onlinechary** [comment]
Getting same issue. Sender is null.  Anyone found a solution for this?

**Comment by lindalu-MSFT** [comment]
@jasonjoh is this a question for stack overflow?

**Comment by sguryev** [comment]
@lindalu-MSFT Does this one look enough? 
https://stackoverflow.com/questions/53831076/is-there-a-way-to-get-the-user-made-an-action

**Comment by jasonjoh** [comment]
I'm double-checking with the team. This may be an issue with your action originating from a Teams client. Outlook should always send the sender claim.

**Comment by jasonjoh** [comment]
I've investigated this with the Actionable Messages team, and this is a limitation of actionable messages received via connectors (either an mailbox/group connector, or a Teams connector).

The user that executed the action is represented by the `sub` claim (the `sender` has nothing to do with that). It's [already documented](https://docs.microsoft.com/outlook/actionable-messages/security-requirements#verifying-that-requests-come-from-microsoft) that for connectors, `sub` contains the object ID, not the email address.

> The identity of the user who took the action. For Actionable Messages sent over email, `sub` would be the email address of the user. For connectors, `sub` will be the objectID of the user who took the action.

This isn't planned to change. For Outlook, you can move to sending your actionable messages via email, and you'll get the `sub` claim as an email address. For Teams, using a connector is the only option.

Regarding the `sender` claim being null: this is also a limitation of the connector flow. The incoming webhook generates an email (or chat message for Teams), but it isn't really "sending" these messages. Because they aren't sent, the sender is never stamped on the message. The logic that determines the sender sees an empty value, so that's what gets put in the token. The easiest way to illustrate this is to look at the "from" field in Outlook for one of these messages, you'll see there's no 
email address:

![image](https://user-images.githubusercontent.com/8966342/82567884-001de380-9b4c-11ea-8e7a-566344ef1176.png)

**Comment by jasonjoh** [comment]
Closing this issue as it isn't a problem with the token validator. I've updated the documentation regarding the `sender` claim behavior.
